require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvXRefsController do

  # This should return the minimal set of attributes required to create a valid
  # InvXRef. As you add validations to InvXRef, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvXRefsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all inv_x_refs as @inv_x_refs" do
      inv_x_ref = InvXRef.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inv_x_refs).should eq([inv_x_ref])
    end
  end

  describe "GET show" do
    it "assigns the requested inv_x_ref as @inv_x_ref" do
      inv_x_ref = InvXRef.create! valid_attributes
      get :show, {:id => inv_x_ref.to_param}, valid_session
      assigns(:inv_x_ref).should eq(inv_x_ref)
    end
  end

  describe "GET new" do
    it "assigns a new inv_x_ref as @inv_x_ref" do
      get :new, {}, valid_session
      assigns(:inv_x_ref).should be_a_new(InvXRef)
    end
  end

  describe "GET edit" do
    it "assigns the requested inv_x_ref as @inv_x_ref" do
      inv_x_ref = InvXRef.create! valid_attributes
      get :edit, {:id => inv_x_ref.to_param}, valid_session
      assigns(:inv_x_ref).should eq(inv_x_ref)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InvXRef" do
        expect {
          post :create, {:inv_x_ref => valid_attributes}, valid_session
        }.to change(InvXRef, :count).by(1)
      end

      it "assigns a newly created inv_x_ref as @inv_x_ref" do
        post :create, {:inv_x_ref => valid_attributes}, valid_session
        assigns(:inv_x_ref).should be_a(InvXRef)
        assigns(:inv_x_ref).should be_persisted
      end

      it "redirects to the created inv_x_ref" do
        post :create, {:inv_x_ref => valid_attributes}, valid_session
        response.should redirect_to(InvXRef.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inv_x_ref as @inv_x_ref" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvXRef.any_instance.stub(:save).and_return(false)
        post :create, {:inv_x_ref => {}}, valid_session
        assigns(:inv_x_ref).should be_a_new(InvXRef)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvXRef.any_instance.stub(:save).and_return(false)
        post :create, {:inv_x_ref => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inv_x_ref" do
        inv_x_ref = InvXRef.create! valid_attributes
        # Assuming there are no other inv_x_refs in the database, this
        # specifies that the InvXRef created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InvXRef.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => inv_x_ref.to_param, :inv_x_ref => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested inv_x_ref as @inv_x_ref" do
        inv_x_ref = InvXRef.create! valid_attributes
        put :update, {:id => inv_x_ref.to_param, :inv_x_ref => valid_attributes}, valid_session
        assigns(:inv_x_ref).should eq(inv_x_ref)
      end

      it "redirects to the inv_x_ref" do
        inv_x_ref = InvXRef.create! valid_attributes
        put :update, {:id => inv_x_ref.to_param, :inv_x_ref => valid_attributes}, valid_session
        response.should redirect_to(inv_x_ref)
      end
    end

    describe "with invalid params" do
      it "assigns the inv_x_ref as @inv_x_ref" do
        inv_x_ref = InvXRef.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvXRef.any_instance.stub(:save).and_return(false)
        put :update, {:id => inv_x_ref.to_param, :inv_x_ref => {}}, valid_session
        assigns(:inv_x_ref).should eq(inv_x_ref)
      end

      it "re-renders the 'edit' template" do
        inv_x_ref = InvXRef.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvXRef.any_instance.stub(:save).and_return(false)
        put :update, {:id => inv_x_ref.to_param, :inv_x_ref => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inv_x_ref" do
      inv_x_ref = InvXRef.create! valid_attributes
      expect {
        delete :destroy, {:id => inv_x_ref.to_param}, valid_session
      }.to change(InvXRef, :count).by(-1)
    end

    it "redirects to the inv_x_refs list" do
      inv_x_ref = InvXRef.create! valid_attributes
      delete :destroy, {:id => inv_x_ref.to_param}, valid_session
      response.should redirect_to(inv_x_refs_url)
    end
  end

end
