require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrxHeadersController do

  # This should return the minimal set of attributes required to create a valid
  # TrxHeader. As you add validations to TrxHeader, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrxHeadersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trx_headers as @trx_headers" do
      trx_header = TrxHeader.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trx_headers).should eq([trx_header])
    end
  end

  describe "GET show" do
    it "assigns the requested trx_header as @trx_header" do
      trx_header = TrxHeader.create! valid_attributes
      get :show, {:id => trx_header.to_param}, valid_session
      assigns(:trx_header).should eq(trx_header)
    end
  end

  describe "GET new" do
    it "assigns a new trx_header as @trx_header" do
      get :new, {}, valid_session
      assigns(:trx_header).should be_a_new(TrxHeader)
    end
  end

  describe "GET edit" do
    it "assigns the requested trx_header as @trx_header" do
      trx_header = TrxHeader.create! valid_attributes
      get :edit, {:id => trx_header.to_param}, valid_session
      assigns(:trx_header).should eq(trx_header)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TrxHeader" do
        expect {
          post :create, {:trx_header => valid_attributes}, valid_session
        }.to change(TrxHeader, :count).by(1)
      end

      it "assigns a newly created trx_header as @trx_header" do
        post :create, {:trx_header => valid_attributes}, valid_session
        assigns(:trx_header).should be_a(TrxHeader)
        assigns(:trx_header).should be_persisted
      end

      it "redirects to the created trx_header" do
        post :create, {:trx_header => valid_attributes}, valid_session
        response.should redirect_to(TrxHeader.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trx_header as @trx_header" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrxHeader.any_instance.stub(:save).and_return(false)
        post :create, {:trx_header => {}}, valid_session
        assigns(:trx_header).should be_a_new(TrxHeader)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrxHeader.any_instance.stub(:save).and_return(false)
        post :create, {:trx_header => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trx_header" do
        trx_header = TrxHeader.create! valid_attributes
        # Assuming there are no other trx_headers in the database, this
        # specifies that the TrxHeader created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TrxHeader.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => trx_header.to_param, :trx_header => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested trx_header as @trx_header" do
        trx_header = TrxHeader.create! valid_attributes
        put :update, {:id => trx_header.to_param, :trx_header => valid_attributes}, valid_session
        assigns(:trx_header).should eq(trx_header)
      end

      it "redirects to the trx_header" do
        trx_header = TrxHeader.create! valid_attributes
        put :update, {:id => trx_header.to_param, :trx_header => valid_attributes}, valid_session
        response.should redirect_to(trx_header)
      end
    end

    describe "with invalid params" do
      it "assigns the trx_header as @trx_header" do
        trx_header = TrxHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrxHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => trx_header.to_param, :trx_header => {}}, valid_session
        assigns(:trx_header).should eq(trx_header)
      end

      it "re-renders the 'edit' template" do
        trx_header = TrxHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrxHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => trx_header.to_param, :trx_header => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trx_header" do
      trx_header = TrxHeader.create! valid_attributes
      expect {
        delete :destroy, {:id => trx_header.to_param}, valid_session
      }.to change(TrxHeader, :count).by(-1)
    end

    it "redirects to the trx_headers list" do
      trx_header = TrxHeader.create! valid_attributes
      delete :destroy, {:id => trx_header.to_param}, valid_session
      response.should redirect_to(trx_headers_url)
    end
  end

end
